### ISSUE TITLE
services.yml incompatible with Symfony 3.3.6

### ISSUE THREAD

**Issue by Gounzy** [azine/email-bundle#21]
When I wanted to update my Symfony project to Symfony 3.3.6,, Composer let me do it (while requerring AzineEmailBundle at dev-master). The problem is that AzineEmailBundle has a services.yml syntax which is no longer accepted in Symfony. The argument names in services declarations need to be like `$name_of_the_php_argument: argument_value` and cannot (anymore) be like `name_of_the_argument: argument_value`. For instance,
 
```yaml
    azine_email.example.template_provider:
        class: Azine\EmailBundle\Services\AzineTemplateProvider
        arguments:
          router:       "@router"
          translator:   "@translator.default"
          parameters:
            image_dir:  "%azine_email_image_dir%"
            allowed_images_folders: "%azine_email_allowed_images_folders%"
            tracking_params_campaign_name:    "%azine_email_tracking_params_campaign_name%"
            tracking_params_campaign_term:    "%azine_email_tracking_params_campaign_term%"
            tracking_params_campaign_content: "%azine_email_tracking_params_campaign_content%"
            tracking_params_campaign_medium:  "%azine_email_tracking_params_campaign_medium%"
            tracking_params_campaign_source:  "%azine_email_tracking_params_campaign_source%"
```
should be replaced by

```yaml
    azine_email.example.template_provider:
        class: Azine\EmailBundle\Services\AzineTemplateProvider
        arguments:
          $router:       "@router"
          $translator:   "@translator.default"
          $parameters:
            image_dir:  "%azine_email_image_dir%"
            allowed_images_folders: "%azine_email_allowed_images_folders%"
            tracking_params_campaign_name:    "%azine_email_tracking_params_campaign_name%"
            tracking_params_campaign_term:    "%azine_email_tracking_params_campaign_term%"
            tracking_params_campaign_content: "%azine_email_tracking_params_campaign_content%"
            tracking_params_campaign_medium:  "%azine_email_tracking_params_campaign_medium%"
            tracking_params_campaign_source:  "%azine_email_tracking_params_campaign_source%"
```

I tried to override this file but I couldn't, which led to an error stipulating that the first argument of service `azine_email.example.template_provide` should be named with the `$` symbol, or by referring its index in the arguments list with an integer. The order of the arguments no longer have a predominant role like it did in previous versions of Symfony.

I know AzineEmailBundle is a Symfony2 bundle, but as Composer allows to use it with Symfony 3.3.6, and as the bundle is completely compatible on the other levels, I wondered: is something going to be done about this? I see two possible fixes: 
- rename arguments with the `$` symbol in services.yml
- omit argument names in services.yml, only relying on their order in the constructor signature
